# Generated by Django 6.0.1 on 2026-03-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Имя задачи"
            ),
        ),
    ]
